# Generated by Django 4.1 on 2025-04-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('average_resp_rate_score', models.FloatField()),
                ('average_po2', models.FloatField()),
                ('sofa_score', models.FloatField()),
                ('ards_label', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('roc_auc', models.FloatField()),
                ('report', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
